/**
 * Render the /examples/ gallery hub from examples/manifest.yaml (E27 S27.3).
 */
import { escapeHtml } from "./html.mjs";

/**
 * @typedef {import("./examples-manifest.mjs").ExamplesManifest} ExamplesManifest
 * @typedef {import("./examples-manifest.mjs").ExampleCatalogEntry} ExampleCatalogEntry
 */

/**
 * Order built catalog entries with the hero first, then remaining catalog order.
 *
 * @param {ExamplesManifest} manifest
 * @param {string[]} builtSlugs
 * @returns {ExampleCatalogEntry[]}
 */
export function orderGalleryEntries(manifest, builtSlugs) {
  const built = new Set(builtSlugs);
  const catalog = manifest.examples.filter((entry) => built.has(entry.slug));
  const hero = catalog.find((entry) => entry.slug === manifest.hero);
  const rest = catalog.filter((entry) => entry.slug !== manifest.hero);
  return hero ? [hero, ...rest] : rest;
}

/**
 * @param {ExampleCatalogEntry} entry
 * @param {boolean} isHero
 * @returns {string}
 */
function renderGalleryCard(entry, isHero) {
  const slug = escapeHtml(entry.slug);
  const title = escapeHtml(entry.title);
  const tagline = escapeHtml(entry.tagline);
  const framework = escapeHtml(entry.framework);
  const href = `${slug}/html/index.html`;
  const cardClass = isHero ? "gallery-card gallery-card--hero" : "gallery-card";
  const badge = isHero
    ? '<span class="gallery-hero-badge">Hero demo</span>'
    : "";

  return `<li class="${cardClass}">
          <a class="gallery-card-link" href="${href}">
            <div class="gallery-card-top">
              <span class="gallery-framework">${framework}</span>
              ${badge}
            </div>
            <h2 class="gallery-card-title">${title}</h2>
            <p class="gallery-card-tagline">${tagline}</p>
            <span class="gallery-card-open">Open live wiki</span>
          </a>
        </li>`;
}

/**
 * Pure manifest → gallery HTML. Only includes `builtSlugs` so hero-only builds
 * never advertise unbuilt demos.
 *
 * @param {ExamplesManifest} manifest
 * @param {{ builtSlugs: string[] }} options
 * @returns {string}
 */
export function renderExamplesGalleryHtml(manifest, { builtSlugs }) {
  if (!Array.isArray(builtSlugs) || builtSlugs.length === 0) {
    throw new Error("build:examples: gallery requires at least one built slug");
  }

  const entries = orderGalleryEntries(manifest, builtSlugs);
  if (entries.length === 0) {
    throw new Error(
      "build:examples: none of the built slugs match the examples catalog",
    );
  }

  const cards = entries
    .map((entry) => renderGalleryCard(entry, entry.slug === manifest.hero))
    .join("\n        ");

  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Examples — [[specwiki]]</title>
    <meta
      name="description"
      content="A gallery of live specwiki wikis — pick the demo closest to your workflow and open a real generated wiki."
    />
    <link rel="icon" href="../assets/favicon.png" type="image/png" sizes="32x32" />
    <link rel="apple-touch-icon" href="../assets/apple-touch-icon.png" sizes="180x180" />
    <link rel="stylesheet" href="../assets/landing.css" />
    <link rel="stylesheet" href="../assets/gallery.css" />
  </head>
  <body>
    <a class="skip-link" href="#main-content">Skip to main content</a>
    <header class="site-header">
      <a href="../index.html" class="specwiki-logo" aria-label="specwiki home">
        <span class="specwiki-logo-bracket" aria-hidden="true">[[</span>specwiki<span class="specwiki-logo-bracket" aria-hidden="true">]]</span>
      </a>
      <nav aria-label="Primary">
        <a class="header-link header-link--active" href="index.html">Examples</a>
        <a class="header-link" href="../blog/index.html">Blog</a>
        <a class="header-link" href="https://github.com/lucasviola/specwiki">GitHub</a>
      </nav>
    </header>

    <main id="main-content" class="gallery-main" tabindex="-1">
      <header class="gallery-header">
        <p class="gallery-kicker">Live examples</p>
        <h1 class="gallery-title">See specwiki on real projects</h1>
        <p class="gallery-lede">
          Every card below is a live wiki generated by specwiki from a real
          example project. Pick the demo closest to your workflow and open the
          full browsable wiki — working search, CSS, and cross-links included.
        </p>
      </header>

      <ul class="gallery-card-list">
        ${cards}
      </ul>
    </main>

    <footer class="site-footer">
      <p>
        <a href="../index.html">specwiki home</a>
        <span class="footer-sep" aria-hidden="true">·</span>
        <a href="../blog/index.html">Blog</a>
        <span class="footer-sep" aria-hidden="true">·</span>
        <a href="https://github.com/lucasviola/specwiki">GitHub</a>
      </p>
    </footer>
  </body>
</html>
`;
}
